### PR TITLE
Update to 1.21

### PR DESCRIPTION
**Pull request by CommandGenius**
1.21 patch for MoreCulling.

### CODE REVIEW

**Comment by wicivo** [comment]
> This is a WIP, this does not work yet.

https://mclo.gs/HJZubwq

**Comment by wicivo** [comment]
Now it's working

**Comment by OriginalUsername01** [comment]
Hello, is it possible for you make a jar file for the port? or is it still not done?

**Comment by Barkells** [comment]
got a compiled jar?

**Comment by wicivo** [comment]
> got a compiled jar?

https://github.com/wicivo/MoreCulling/actions/runs/9664028108

**Comment by Cartrigger** [comment]
https://github.com/FxMorin/MoreCulling/assets/81428538/93bee8bf-a32e-4862-940d-c3a9160a7c19

Seems like it doesn't like transparency

**Comment by FxMorin** [comment]
@Cartrigger What do you mean? Like in the mod menu or in game?

**Comment by Cartrigger** [comment]
https://github.com/FxMorin/MoreCulling/assets/81428538/8d9143c6-8652-4661-baff-615f331f990a

There's blur for the tooltips, I dont think that is intended, because on the right on 1.20.6 it does not happen, though they are both black which may or may not be intended

**Comment by CommandGenius** [comment]
There's also a bug where holding stained glass on Fabulous graphics makes the stained glass invisible only while holding it. I haven't tested this on 1.20.6.

**Comment by CommandGenius** [comment]
> It looks like it has to do with ItemRenderer_faceCullingMixin.java

specifically moreculling$skipSlowTransparencyChecks

**Comment by ActuallyTheOwner** [comment]
I do see this is waiting approval
Hope everything passes!

**Comment by tajemniktv** [comment]
After some testing I didn't find many issues, mind you I'm playing on a 300+ modpack that mostly modifies the client side (performance, resources, guis, visuals etc.) - I had issues with closed trapdoors, that had their underneath (in the windows) culled, which was basically an X-Ray. Might be worth looking into. Disabling blostate culling helped with that

**Pull request merged**
