### PR TITLE
Update et_ee.json

### PR DESCRIPTION
**Pull request by Madis0**

### CODE REVIEW

**Comment by fxmorin** [comment]
Once I commit changes I've made, there is another line that needs to be changed. So ill hold this until then

**Comment by fxmorin** [comment]
Ok there you go, add the new translations to be included in v0.6.1

**Comment by Madis0** [comment]
Should be all now.

**Comment by fxmorin** [comment]
Sorry going to delay this more, I want to add powder snow culling to v0.6.1 also

**Comment by fxmorin** [comment]
Ok add the new translations and we should be good for v0.6.1

**Pull request merged**
